### ISSUE TITLE
 list index out of range

### ISSUE THREAD

**Issue by Az0s** [LAWTED/BUPT-Auto-Syllabu#1]
[▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▊] [99.00%]Traceback (most recent call last):
  File ".\process.py", line 266, in <module>
    week_item_end = week_item.split('-')[1]
IndexError: list index out of range

**Comment by LAWTED** [comment]
U can send me you .xls file which can be download from jwgl.bupt.edu.cn and send to wmz@bupt.edu.cn

**Comment by LAWTED** [comment]
TRY it again,it should work,thx for your issue
