### ISSUE TITLE
Thx for your work, but I think there is something wrong.

### ISSUE THREAD

**Issue by Sinclairwww** [LAWTED/BUPT-Auto-Syllabu#2]
Sorry I didn't learn anything about python so maybe my problem is kinda stupid. 
After I followed your direction (1. pip  2. python)  in Windows (cmd) and input my ID and password, the last thing it displayed was:

-------------------------------------------------------------------------------------------------------------------------------------------------
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='jwgl.bupt.edu.cn', port=443): Max retries exceeded with url: /jsxsd/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022B058C9960>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-------------------------------------------------------------------------------------------------------------------------------------------------

I don't know why it didn't work.

**Comment by Sinclairwww** [comment]
ps: ... I can't find the direct.txt

**Comment by LAWTED** [comment]
i update the readme and u can just access to lawted.tech and get your syllabus

**Comment by LAWTED** [comment]
> Sorry I didn't learn anything about python so maybe my problem is kinda stupid. After I followed your direction (1. pip 2. python) in Windows (cmd) and input my ID and password, the last thing it displayed was:
> 
> ## requests.exceptions.ConnectionError: HTTPSConnectionPool(host='jwgl.bupt.edu.cn', port=443): Max retries exceeded with url: /jsxsd/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022B058C9960>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
> I don't know why it didn't work.

cuz we are not under the Campus Network, but if  u use version 2 there is no need for campus network

**Comment by Sinclairwww** [comment]
Version 2 worked! Thx!!!  I will try the first version when I go back to school.
